Repository joye-seo/Sixtagram, pull requests merged in 2023-08, with the labels that each got.

#13 Feature/member4
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/res/drawable/ic_line_horizon.xml
  app/src/main/res/drawable/ic_member_circledimage.xml
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/activity_member_detail.xml
  app/src/main/res/layout/activity_member_modify.xml
  app/src/main/res/values/colors.xml
Labels: UI

#14 [FEAT] 힌트버튼 죽이는거랑 하드모드 구현
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameStartActivity.kt
  app/src/main/res/layout/activity_gamemain.xml
  app/src/main/res/layout/activity_gamestart.xml
Labels: enhancement

#15 [FEAT] : ⚙️회원 가입 기능 추가 및 아이디 중복 확인, 비밀번호 체크 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/login/LoginActivity.kt
  app/src/main/java/com/example/sixtagram/login/SignUpActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#16 [UI]달력 UI 개선!
  app/src/main/java/com/example/sixtagram/calendar/CalendarActivity.kt
  app/src/main/res/layout/activity_calendar.xml
Labels: UI

#17 Feature/member5
  app/build.gradle
  app/src/main/java/com/example/sixtagram/member/MemberActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemberDetailActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemberModifyActivity.kt
  app/src/main/res/drawable/ic_member_circledimage.xml
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/activity_member_detail.xml
  app/src/main/res/layout/activity_member_modify.xml
Labels: enhancement, UI

#18 [UI]메모장 버튼 & 메모장 툴 구현!!
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/calendar/CalendarActivity.kt
  app/src/main/java/com/example/sixtagram/calendar/CalendarListAdapter.kt
  app/src/main/java/com/example/sixtagram/calendar/CalendarModel.kt
  app/src/main/java/com/example/sixtagram/calendar/NotionTextEditActivity.kt
  app/src/main/res/drawable/ic_notifications.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_notion_text_edit.xml
Labels: enhancement, UI

#19 [FEAT] : ⚙️회원 가입 시 비밀번호 최소 6자리 이상, 특수 문자, 영문, 숫자를 입력 해야
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/sixtagram/login/SignUpActivity.kt
  app/src/main/res/layout/activity_sign_up.xml
Labels: enhancement

#20 [UI] CommunityActivity 화면 구현
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/community/CommunityActivity.kt
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/shape_comment_background.xml
  app/src/main/res/drawable/shape_comment_like_background.xml
  app/src/main/res/drawable/shape_list_subject_background.xml
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/layout/item_community_comment.xml
  app/src/main/res/menu/community_topic_menu.xml
  app/src/main/res/raw/lottie_heart.json
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: UI

#21 [FEAT] : ⚙️ 거주지 입력시 아이디와 비번 찾기 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/login/LoginActivity.kt
  app/src/main/java/com/example/sixtagram/login/MemberFindActivity.kt
  app/src/main/java/com/example/sixtagram/login/SignUpActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_member_find.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: bug, enhancement

#22 [bug] : ⚙️ 로그인 페이지에 이메일과 비밀 번호 값이 남아 있는 오류 수정
  app/src/main/java/com/example/sixtagram/login/LoginActivity.kt
Labels: bug

#23 [UI]달력 텍스트 출력 형식 변경!!
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/calendar/CalendarActivity.kt
  app/src/main/java/com/example/sixtagram/calendar/MemoActivity.kt
  app/src/main/java/com/example/sixtagram/calendar/NotionTextEditActivity.kt
  app/src/main/res/drawable/ic_back2.png
  app/src/main/res/drawable/ic_diskette.png
  app/src/main/res/drawable/ic_document.png
  app/src/main/res/drawable/ic_draw.png
  app/src/main/res/drawable/ic_trash.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_memo.xml
Labels: bug, enhancement, UI

#25 [FEAT] 일시정지 구현, 점수수식 구현, 랭킹보드 구현,
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/sixtagram/game/GameEndActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/res/layout/activity_gameend.xml
  app/src/main/res/layout/activity_gamemain.xml
Labels: enhancement

#26 [Feat] Community 기능 개발
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/community/CommunityActivity.kt
  app/src/main/java/com/example/sixtagram/community/CommunityAdapter.kt
  app/src/main/java/com/example/sixtagram/community/CommunityAddActivity.kt
  app/src/main/java/com/example/sixtagram/community/CommunityData.kt
  app/src/main/java/com/example/sixtagram/community/CommunityDetailActivity.kt
  app/src/main/res/drawable/ic_heart.png
  app/src/main/res/drawable/shape_comment_like_background.xml
  app/src/main/res/drawable/shape_list_subject_background.xml
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/item_community.xml
Labels: enhancement, UI

#27 [Feat] GameActivity 여러가지 기능 추가 및 설명 액티비티 하나 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/game/GameDescriptionActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameEndActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameStartActivity.kt
  app/src/main/res/layout/activity_game_description.xml
  app/src/main/res/layout/activity_gameend.xml
  app/src/main/res/layout/activity_gamemain.xml
  app/src/main/res/layout/activity_gamestart.xml
Labels: enhancement

#28 [DESIGN][FEAT] Community 댓글 디자인 리스트뷰 추가 + 전체 폰트 관리를 위해 theme 적용
  app/src/main/java/com/example/sixtagram/adapter/CommentAdapter.kt
  app/src/main/java/com/example/sixtagram/adapter/CommunityAdapter.kt
  app/src/main/java/com/example/sixtagram/calendar/CalendarActivity.kt
  app/src/main/java/com/example/sixtagram/community/CommunityActivity.kt
  app/src/main/java/com/example/sixtagram/community/CommunityAddActivity.kt
  app/src/main/java/com/example/sixtagram/community/CommunityDetailActivity.kt
  app/src/main/java/com/example/sixtagram/data/Comment.kt
  app/src/main/java/com/example/sixtagram/data/Community.kt
  app/src/main/java/com/example/sixtagram/data/CommunityRelated.kt
  app/src/main/java/com/example/sixtagram/member/MemberActivity.kt
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/layout/item_community_comment.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, UI

#30 Feature/login design3
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/login/LoginActivity.kt
  app/src/main/java/com/example/sixtagram/login/MemberFindActivity.kt
  app/src/main/java/com/example/sixtagram/login/SignUpActivity.kt
  app/src/main/java/com/example/sixtagram/memberData/Member.kt
  app/src/main/java/com/example/sixtagram/memberData/MemberData.kt
  app/src/main/java/com/example/sixtagram/memberData/MemberHashmap.kt
  app/src/main/res/drawable/ic_login_password.png
  app/src/main/res/drawable/ic_login_password5.png
  app/src/main/res/drawable/ic_login_password6.xml
  app/src/main/res/drawable/ic_login_person2.png
  app/src/main/res/drawable/ic_login_person3.xml
  app/src/main/res/drawable/ic_login_sparta.png
  app/src/main/res/drawable/ic_login_sparta2.png
  app/src/main/res/drawable/ic_sign_up_blog.png
  app/src/main/res/drawable/ic_sign_up_blog2.xml
  app/src/main/res/drawable/ic_sign_up_concern.png
  app/src/main/res/drawable/ic_sign_up_concern2.xml
  app/src/main/res/drawable/ic_sign_up_github.png
  app/src/main/res/drawable/ic_sign_up_github2.xml
  app/src/main/res/drawable/ic_sign_up_hobby.png
  app/src/main/res/drawable/ic_sign_up_hobby2.xml
  app/src/main/res/drawable/ic_sign_up_home.png
  app/src/main/res/drawable/ic_sign_up_home2.xml
  app/src/main/res/drawable/ic_sign_up_mbti.png
  app/src/main/res/drawable/ic_sign_up_mbti2.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_member_find.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#31 [UI]메모장 UI 카테고리 틀 작업!!0818
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/calendar/CalendarActivity.kt
  app/src/main/java/com/example/sixtagram/calendar/MemoActivity.kt
  app/src/main/java/com/example/sixtagram/calendar/NotionTextEditActivity.kt
  app/src/main/res/drawable/ic_add.png
  app/src/main/res/drawable/ic_add_button.png
  app/src/main/res/drawable/ic_back_button.png
  app/src/main/res/drawable/ic_check.png
  app/src/main/res/drawable/ic_copywriting.png
  app/src/main/res/drawable/ic_edit.png
  app/src/main/res/drawable/ic_left_arrow.png
  app/src/main/res/drawable/ic_new_calendar.png
  app/src/main/res/drawable/ic_pen.png
  app/src/main/res/drawable/ic_pencil.png
  app/src/main/res/drawable/ic_trash2.png
  app/src/main/res/drawable/ic_turn_back.png
  app/src/main/res/drawable/ic_warning_sign.png
  app/src/main/res/drawable/ic_written_paper.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_memo.xml
  app/src/main/res/layout/activity_notion_text_edit.xml
Labels: bug, enhancement, UI

#32 [MODIFY] AndroidManifest 삭제된 클래스 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/community/CommunityDetailActivity.kt
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/values/themes.xml
Labels: bug

#33 [FEAT] 댓글 추가 기능 일부 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/adapter/CommentAdapter.kt
  app/src/main/java/com/example/sixtagram/community/CommunityActivity.kt
  app/src/main/java/com/example/sixtagram/community/CommunityAddActivity.kt
  app/src/main/java/com/example/sixtagram/community/CommunityDetailActivity.kt
  app/src/main/java/com/example/sixtagram/data/Comment.kt
  app/src/main/java/com/example/sixtagram/data/Community.kt
Labels: enhancement, UI

#34 [memberActivity] 리스트뷰 인텐트 구현 및 오류 수정
  app/build.gradle
  app/src/main/java/com/example/sixtagram/member/MemDelDialogActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemDelDialogInterface.kt
  app/src/main/java/com/example/sixtagram/member/MemUser.kt
  app/src/main/java/com/example/sixtagram/member/MemUserAdap.kt
  app/src/main/java/com/example/sixtagram/member/MemberActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemberDetailActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemberModifyActivity.kt
  app/src/main/res/drawable/ic_member_rainbow.png
  app/src/main/res/drawable/member_profile_dkl.jpg
  app/src/main/res/drawable/member_profile_msk.jpg
  app/src/main/res/drawable/member_profile_shs.jpg
  app/src/main/res/drawable/member_profile_sjl.png
  app/src/main/res/drawable/member_profile_wjc.jpg
  app/src/main/res/layout/activity_mem_del_dialog.xml
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/activity_member_detail.xml
  app/src/main/res/layout/activity_member_modify.xml
  app/src/main/res/layout/activity_memuseractivity.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement, invalid, UI

#35 [UI],[Enhancement]영어,한글 String으로 지원 완료 0819
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/calendar/CalendarActivity.kt
  app/src/main/java/com/example/sixtagram/calendar/MemoActivity.kt
  app/src/main/java/com/example/sixtagram/calendar/NotionTextEditActivity.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_memo.xml
  app/src/main/res/layout/activity_notion_text_edit.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#36 [Feature] 폰트에 style적용
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_mem_del_dialog.xml
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/activity_member_detail.xml
  app/src/main/res/layout/activity_member_modify.xml
  app/src/main/res/layout/activity_memuseractivity.xml
Labels: documentation

#37 [DESIGN]: UI 위치 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/login/SignUpActivity.kt
  app/src/main/java/com/example/sixtagram/memberData/Member.kt
  app/src/main/java/com/example/sixtagram/memberData/MemberData.kt
  app/src/main/java/com/example/sixtagram/memberData/MemberHashmap.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_member_find.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#39 [Modify] : ⚙️ 회원 가입 페이지 오타 수정
  app/src/main/java/com/example/sixtagram/login/SignUpActivity.kt
Labels: bug

#40 Feature/game design
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/sixtagram/game/GameDescriptionActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameEndActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameStartActivity.kt
  app/src/main/res/drawable/ic_game_difficulty.png
  app/src/main/res/drawable/ic_game_hint.png
  app/src/main/res/drawable/ic_game_infomation.png
  app/src/main/res/drawable/ic_game_numberrange.png
  app/src/main/res/drawable/ic_game_paused.png
  app/src/main/res/drawable/ic_game_played.png
  app/src/main/res/drawable/ic_game_ranking.png
  app/src/main/res/drawable/ic_game_restart.png
  app/src/main/res/drawable/ic_game_rule.png
  app/src/main/res/drawable/ic_game_settings.png
  app/src/main/res/drawable/ic_game_tool.png
  app/src/main/res/drawable/selector_game_button.xml
  app/src/main/res/drawable/selector_game_text.xml
  app/src/main/res/layout/activity_game_description.xml
  app/src/main/res/layout/activity_gameend.xml
  app/src/main/res/layout/activity_gamemain.xml
  app/src/main/res/layout/activity_gamestart.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#41 [Modify] strings.xml 머지하다 충돌나서 생긴 누락분 추가한 후 푸쉬
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#42 [Modify] strings.xml, 폰트사이즈 수정 ,gif추가, 레이아웃 수정
  app/build.gradle
  app/src/main/java/com/example/sixtagram/game/GameDescriptionActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameEndActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameStartActivity.kt
  app/src/main/res/drawable/ic_game_rankbackground.gif
  app/src/main/res/drawable/ic_game_rankreset.png
  app/src/main/res/layout/activity_game_description.xml
  app/src/main/res/layout/activity_gameend.xml
  app/src/main/res/layout/activity_gamemain.xml
  app/src/main/res/layout/activity_gamestart.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#43 [Feature] listView, adaptor, selector 오류 수정
  app/src/main/java/com/example/sixtagram/member/MemDetailAdap.kt
  app/src/main/java/com/example/sixtagram/member/MemUser.kt
  app/src/main/java/com/example/sixtagram/member/MemUserAdap.kt
  app/src/main/java/com/example/sixtagram/member/MemberActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemberDetailActivity.kt
  app/src/main/java/com/example/sixtagram/memberData/Member.kt
  app/src/main/java/com/example/sixtagram/memberData/MemberData.kt
  app/src/main/res/layout/activity_member_detail.xml
  app/src/main/res/layout/activity_member_modify.xml
Labels: bug, enhancement, UI

#44 [UI] SplashActivity 로고 추가, CommunityAddActivity UI 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/SplashActivity.kt
  app/src/main/java/com/example/sixtagram/adapter/CommunityAdapter.kt
  app/src/main/java/com/example/sixtagram/community/CommunityAddActivity.kt
  app/src/main/java/com/example/sixtagram/data/Community.kt
  app/src/main/java/com/example/sixtagram/data/CommunityRelated.kt
  app/src/main/res/drawable/ic_sixtagram.png
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: UI

#45 [Modify] strings.xml 추가
  app/src/main/java/com/example/sixtagram/game/GameEndActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameStartActivity.kt
  app/src/main/res/layout/activity_game_description.xml
  app/src/main/res/layout/activity_gameend.xml
  app/src/main/res/layout/activity_gamemain.xml
  app/src/main/res/layout/activity_gamestart.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#46 [UI, Modify, Enhancement]
  app/src/main/java/com/example/sixtagram/member/MemberDetailActivity.kt
  app/src/main/java/com/example/sixtagram/memberData/Member.kt
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/activity_member_detail.xml
  app/src/main/res/layout/activity_member_modify.xml
Labels: documentation, enhancement, UI

#47 Feature/game design
  app/src/main/java/com/example/sixtagram/game/GameEndActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameStartActivity.kt
  app/src/main/res/drawable/ic_game_return_to_start.png
  app/src/main/res/layout/activity_gameend.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#48 [Modify] finish() 빼먹어서 추가
  app/src/main/java/com/example/sixtagram/game/GameEndActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameStartActivity.kt
  app/src/main/res/layout/activity_gameend.xml
Labels: enhancement

#49 [UI] 카테고리 글자색 변경 빽그라운드 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/calendar/MemoActivity.kt
  app/src/main/res/layout/activity_memo.xml
  app/src/main/res/layout/spinner_item.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, UI

#50 [Design] 지옥모드 한정 백그라운드 이미지 추가
  app/src/main/java/com/example/sixtagram/game/GameMainActivity.kt
  app/src/main/res/drawable/ic_game_hell.jpg
  app/src/main/res/layout/activity_gamemain.xml
Labels: enhancement

#51 [Enhance,UI]
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/member/MemUser.kt
  app/src/main/java/com/example/sixtagram/member/MemberActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemberDetailActivity.kt
  app/src/main/java/com/example/sixtagram/memberData/Member.kt
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/activity_member_detail.xml
  app/src/main/res/layout/activity_member_modify.xml
Labels: bug, enhancement, UI

#52 [bug] : ⚙️ 로그인 페이지에서 잘못된 아이디 와 비밀 번호 입력시 생긴 null 값 오류 해결
  app/src/main/java/com/example/sixtagram/login/LoginActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemberActivity.kt
Labels: bug

#53 [UI / ENHANCEMENT] Splash2 기능개발
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sixtagram/Splash2Activity.kt
  app/src/main/java/com/example/sixtagram/adapter/CommentAdapter.kt
  app/src/main/java/com/example/sixtagram/adapter/CommunityAdapter.kt
  app/src/main/java/com/example/sixtagram/community/CommunityActivity.kt
  app/src/main/java/com/example/sixtagram/community/CommunityDetailActivity.kt
  app/src/main/java/com/example/sixtagram/login/LoginActivity.kt
  app/src/main/res/drawable/img_splash.jpeg
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_splash2.xml
Labels: enhancement, UI

#55 [Documentation] README. 추가
  .idea/deploymentTargetDropDown.xml
  README.md
  app/src/main/java/com/example/sixtagram/adapter/MemUserAdap.kt
  app/src/main/java/com/example/sixtagram/data/Member.kt
  app/src/main/java/com/example/sixtagram/data/MemberData.kt
  app/src/main/java/com/example/sixtagram/data/MemberHashmap.kt
  app/src/main/java/com/example/sixtagram/game/GameEndActivity.kt
  app/src/main/java/com/example/sixtagram/game/GameStartActivity.kt
  app/src/main/java/com/example/sixtagram/login/LoginActivity.kt
  app/src/main/java/com/example/sixtagram/login/MemberFindActivity.kt
  app/src/main/java/com/example/sixtagram/login/SignUpActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemDetailAdap.kt
  app/src/main/java/com/example/sixtagram/member/MemberActivity.kt
  app/src/main/java/com/example/sixtagram/member/MemberDetailActivity.kt
Labels: documentation
